services:
  netbox:
    ports:
    - 8080:8080
    volumes:
    - /var/lib/docker/volumes/netbox-config-files/_data:/etc/netbox/config:z,ro
    - /var/lib/docker/volumes/netbox-media-files/_data:/opt/netbox/netbox/media:z,rw
    - /var/lib/docker/volumes/netbox-reports-files/_data:/opt/netbox/netbox/reports:z,rw
    - /var/lib/docker/volumes/netbox-scripts-files/_data:/opt/netbox/netbox/scripts:z,rw
    healthcheck:
      retries: 15
  netbox-worker:
    volumes:
    - /var/lib/docker/volumes/netbox-config-files/_data:/etc/netbox/config:z,ro
    - /var/lib/docker/volumes/netbox-media-files/_data:/opt/netbox/netbox/media:z,rw
    - /var/lib/docker/volumes/netbox-reports-files/_data:/opt/netbox/netbox/reports:z,rw
    - /var/lib/docker/volumes/netbox-scripts-files/_data:/opt/netbox/netbox/scripts:z,rw
  netbox-housekeeping:
    volumes:
    - /var/lib/docker/volumes/netbox-config-files/_data:/etc/netbox/config:z,ro
    - /var/lib/docker/volumes/netbox-media-files/_data:/opt/netbox/netbox/media:z,rw
    - /var/lib/docker/volumes/netbox-reports-files/_data:/opt/netbox/netbox/reports:z,rw
    - /var/lib/docker/volumes/netbox-scripts-files/_data:/opt/netbox/netbox/scripts:z,rw
